### ISSUE TITLE
Prevent compiling partial .scss files

### ISSUE THREAD

**Issue by fredbutters** [delegateas/Delegate.SassBuilder#1]
Is there anyway to prevent this tool from compiling the partial .scss files (ex: _style.scss)?

Currently, any .scss file will generate a corresponding .css file.

**Comment by soerennielsen** [comment]
No, it just runs through all .scss files.

I could change it though... Is the "_" convention used by everyone? Will it
make sense to make the default behaviour ignore the underscore files?

**Comment by fredbutters** [comment]
@soerennielsen that's correct.

"The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file."
- http://sass-lang.com/guide
  
  Thanks!

**Comment by soerennielsen** [comment]
Done. 

Update to version 1.4.0.
